

[acl]

# List of Python regex patterns 
match_patterns = [
    "(<:gamerwhen:651367432967159808>)+" # Matches :gamerwhen: emojis
]

# List of channel IDs that regular users can roll on.
# Note that Administrators and Moderators can trigger the roll on any channel regardless.
channels = [
    "1200075107373170698", # gamerwhen
    "1078358866770792489", # mad-science
]

# List of Discord Roles
# These roles will be immune to being timed out.
protected = [
    "546422996810727434", # Best Friends
    "1061611797133668423", # Ice Guy
    "1157317681159098448", # Rakka
    "889103199624118322", # 爆発隊
]

# List of Discord Roles
# These roles will be able to roll for other roles.
# Moderators are implicitly protected users.
moderator = [
    "644057450743595010", # Sheriffs
    "986229557659045899", # Deputies
]

# List of Discord User IDs
# Reserved superuser role for future use.
# Administrators are implicitly moderators.
administrator = [
    "146619230760992768", # elvengarde
]

[messages]
# A list of messages that could be used to reply to a user who timed themselves out.
# Supported inline variables:
# {timeout_user_name}: The display name of the user (will not be tagged)
# {timeout_duration_label}: A display of the user's timeout duration
timeout_affected_messages_self = [
    "Hitdad sees and Hitdad strikes. {timeout_user_name} is muted for {timeout_duration_label}.",
    "Daughter protection. It's to die for. {timeout_user_name} is muted for {timeout_duration_label}.",
    "Waluigi. He's to die for. {timeout_user_name} is muted for {timeout_duration_label}.",
    "What's the most you ever lost on a coin toss? {timeout_user_name} wagered {timeout_duration_label}.",
    "Reverend Waluigi has deemed {timeout_user_name} a sinner. Their penance: A vow of silence for {timeout_duration_label}.",
    "General Waluigi has sent {timeout_user_name}'s squad on a secret mission to spread the Word of Wah. They will be radio-silent for {timeout_duration_label}.",
    "Eyeless dogs are prowling around {timeout_user_name}'s house. They'll go away after {timeout_duration_label}.",
    "Moe loves you {timeout_user_name}, but you're still getting muted for {timeout_duration_label}."
]

# A list of a messages that could be used to reply to a moderator or administrator who timed another user out.
# Supported inline variables:
# {timeout_user_name}: The display name of the user (will not be tagged)
# {timeout_duration_label}: A display of the user's timeout duration
timeout_affected_messages_other = [
    "Hitdad sees and Hitdad strikes. {timeout_user_name} is muted for {timeout_duration_label}.",
    "Daughter protection. It's to die for. {timeout_user_name} is muted for {timeout_duration_label}.",
    "Waluigi. He's to die for. {timeout_user_name} is muted for {timeout_duration_label}.",
    "What's the most you ever lost on a coin toss? {timeout_user_name} wagered {timeout_duration_label}.",
    "Reverend Waluigi has deemed {timeout_user_name} a sinner. Their penance: A vow of silence for {timeout_duration_label}.",
    "General Waluigi has sent {timeout_user_name}'s squad on a secret mission to spread the Word of Wah. They will be radio-silent for {timeout_duration_label}.",
    "Eyeless dogs are prowling around {timeout_user_name}'s house. They'll go away after {timeout_duration_label}.",
]

# A list of messages that could be used to reply to a user who attempted to time themselves out, but was protected.
# Supported inline variables:
# {timeout_user_name}: The display name of the user (will not be tagged)
# {timeout_duration_label}: A display of the user's timeout duration
timeout_protected_messages_self = [
    "Moe loves you, so you won't get muted for {timeout_duration_label}.",
    "The love of Moe's life, thou art not deserving of a {timeout_duration_label} mute."
]

# A list of messages that could be used to reply to a moderator or administrator who attempted to timeout a protected user.
# Supported inline variables:
# {timeout_user_name}: The display name of the user (will not be tagged)
# {timeout_duration_label}: A display of the user's mute duration
timeout_protected_messages_other = [
    "The love of Moe's life, {timeout_user_name} is not deserving of a {timeout_duration_label} mute."
]